### ISSUE TITLE
Org Chart: Chart does not display new child org unless user forces a refresh of the page

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#444]
When user creates a child org, the UI sends the user from the org chart page to the child org creation page and then returns them to the chart. When they come back to that screen, though, their new child org is not visible. They have to refresh the page to see their org in the chart to be able to navigate back into it. This is cumbersome, especially when the dataseeder has a large number of children orgs to add as well. Perhaps there is a caching issue? We don't want to show the user out of date info. See attached.

EXPECTED: Page is refreshed when user adds a child org.

![RefreshIssue](https://user-images.githubusercontent.com/49886260/61086005-963e9480-a3e6-11e9-9175-dbde9995c3ab.gif)

**Comment by arvindkhatik012** [comment]
We have fixed the issue now it was happening due to caching

**Comment by BethRR** [comment]
@akhilesh-94 I am still seeing this issue -- maybe the code wasn't deployed?

**Comment by akhilesh-94** [comment]
> @akhilesh-94 I am still seeing this issue -- maybe the code wasn't deployed?

Issue seems to be with caching on server-side. We are looking into it

**Comment by arvindkhatik012** [comment]
we have fixed the issue now

**Comment by BethRR** [comment]
@arvindkhatik012 @akhilesh-94 - I am still seeing the issue except now the child count is momentarily correct (8 children) and then changes back down to 7 children as seen in attached gif (14 seconds in)
![refresh_issue](https://user-images.githubusercontent.com/49886260/61254757-8f7f8c80-a71a-11e9-90ec-af0dbc93a2d2.gif)

**Comment by BethRR** [comment]
Thank you @arvindkhatik012 and @akhilesh-94 ! Closing as fixed.
