### ISSUE TITLE
Upload Notification not sending notification when upload job fails

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#483]
John attempted to upload 2 files at 11am (PST) on 7/19/2019 that seems to have failed, but no notification was received. The two files each had only 1k rows which should take ~6 min each based on our observation of past time trends. Notification should be sent when a job fails.

We know the job failed because we saw no change in the number of orgs in the system.

**Comment by arvindkhatik012** [comment]
Hi @Beth Roberts @John Raynolds,
we tried to replicate the git  issue https://github.com/winwinwiki/winwin-frontend/issues/483, https://github.com/winwinwiki/winwin-frontend/issues/484 and uploaded the two files each with 1k organizations at the same time and it worked fine.

Click the below link to Check the success notifications and time stamp. 
https://winwin2016.slack.com/archives/CL45P64BA/p1563613816000400
https://winwin2016.slack.com/archives/CL45P64BA/p1563613852000700

**Comment by BethRR** [comment]
@arvindkhatik012 -- Any suggestion for how can we test notification of a failed upload? That's what this issue is related to.

**Comment by sunnytambi** [comment]
@BethRR , the success and failure updates both comes in "notifications_upload" channel in slack.

**Comment by arvindkhatik012** [comment]
@BethRR , As an example of failed organization we have tried once case where we have assigned a wrong parent_id to the organization was failed to upload due to the foreign_key constraint didn't met.

Attaching the result file as well as the csv file for your reference.

Thanks

[test_failed_organization.zip](https://github.com/winwinwiki/winwin-frontend/files/3422143/test_failed_organization.zip)

**Comment by BethRR** [comment]
Appears to be fixed

**Comment by BethRR** [comment]
Still not seeing notification when an upload fails. For example, I loaded two files yesterday with incorrect schemas and received no errors in the tool. As expected, the files did not appear to load. An upload notification should have been sent to let us know that the upload failed (and why).

**Comment by arvindkhatik012** [comment]
@BethRR Can you please send the files on slack that you have uploaded. We will replicate the issue.

**Comment by arvindkhatik012** [comment]
we have fixed the issue. now the WinWinWiki editor bulk upload status file will

**Comment by BethRR** [comment]
Still not seeing a notification of failure when an upload job fails.

**Comment by arvindkhatik012** [comment]
@BethRR As I explained on the call, the failed organization will be available in bulk upload status file with status as FAILED and Comment will have the exact error.

**Comment by arvindkhatik012** [comment]
@BethRR We checked the issue and found that the error occured due to use of incorrect template .
You have used fields SDG Tags , SPI tags instead of spiTagIds and sdgTagIds and because of that system was not able to recognize the correct fields mapping.

Note: Please download the template first and than try to upload again or update your template with correct field name.
[admin_bulk_create_template .csv.txt](https://github.com/winwinwiki/winwin-frontend/files/3824124/admin_bulk_create_template.csv.txt)

![image](https://user-images.githubusercontent.com/45760420/68469499-4e1e6a00-0240-11ea-878f-d067b4f03dfa.png)

**Comment by sunnytambi** [comment]
[Bulk_Upload_TEST_IRS_WA_BETH_TEST.zip](https://github.com/winwinwiki/winwin-frontend/files/3863186/Bulk_Upload_TEST_IRS_WA_BETH_TEST.zip)

Fixed by showing notification on UI for the attached test file.
