### ISSUE TITLE
Inconsistent browser 'Back' button returns user to wrong page or labels the page incorrectly (goes back two pages)

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#628]
This is a tricky bug to repro, so I've included a video. It seems to behave very inconsistently. Because it is so unpredictable and can lead users to create bad data, I am setting as a Pri 1. Also attached is the Http Archive file.

[BackButtonIssue.zip](https://github.com/winwinwiki/winwin-frontend/files/3531999/BackButtonIssue.zip)

**To attempt to repro:** 
1) From org management, open and review a few different orgs (Orgs A-C), paying close attention to which orgs you review

2) Open another org (Org X) and navigate to the the SDG page, then click the browser back button. 
Note that rather than rather than returning the user to org basic info page, it appears to take them to the basic info page for a previous org (possibly Org A). 

I say appears because the breadcrumb displays the name of the Org A (rather than Org X), but the URL appears to be correct.

When I look at the network tab of the developer console, it looks like that back-end and front end headers are looking for different org ids.

[stage.winwin.care_HAR.txt](https://github.com/winwinwiki/winwin-frontend/files/3532022/stage.winwin.care_HAR.txt)

**Comment by sunnytambi** [comment]
Fixed. Please check.

**Comment by JRWinWin** [comment]
This issue is still present, but has changed in nature so I will explain the current issue here. Testing done in Chrome.
Repro: 1. From Organization Management, select an organization.
2. In sequence navigate to the Organization chart, then Programs, then Notes. 
3. Now press the browser's back button. You will see this situation: 
![Backspace Image #1](https://user-images.githubusercontent.com/48923883/64554707-cb853700-d2f0-11e9-8d56-0f47c69c4c0f.png)

4. Now press the browser's back button again. You will see this situation: 
![Backspace Image #2](https://user-images.githubusercontent.com/48923883/64554952-35054580-d2f1-11e9-9199-0db8869be545.png)

5. Now press the browser's back button again. You will see this situation: 
![Backspace image #3](https://user-images.githubusercontent.com/48923883/64555030-5c5c1280-d2f1-11e9-942e-5590ee97ee5d.png)


It seems the parts of the page are not in accordance with each other as backspace is used. 
These parts of the page need to be aligned.

**Comment by sunnytambi** [comment]
Hi @JRWinWin , It may have been because the fixes weren't pushed to staging earlier. Now the fixes are available on staging. Please check this again.
