### ISSUE TITLE
Create User - "Enter Valid Name" incorrectly appearing

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#660]
<img width="1250" alt="User Creation - Enter Valid Name" src="https://user-images.githubusercontent.com/48923883/64198812-d0a03d00-ce3d-11e9-8476-08353c85e797.png">

Issue: While creating a new user, the "Enter Valid Name" error notification comes up even when the name is valid. This error prevents any users from being created. Users must be able to enter any name into the Full Name field in User Creation and create new users.

**Comment by JRWinWin** [comment]
Issue: While creating a new user, the "Enter Valid Name" error notification comes up even when the name is valid. **Correction:** This **error does not prevent** any users from being created. Users must be able to enter any name into the Full Name field in User Creation and create new users.

**Comment by sunnytambi** [comment]
Resolved . Please check.

**Comment by JRWinWin** [comment]
![User Creation Valid Name Error Still](https://user-images.githubusercontent.com/48923883/64543710-8ce48200-d2da-11e9-805a-4166f39a6d9b.png)

This issue is still present. 
I am testing in staging.

**Comment by JRWinWin** [comment]
This issue is resolved
